name: Start Web Server

on: [push]

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: node server.js

    - name: Open browser
      run: |
        echo "Opening browser..."
        export DISPLAY=:99
        sudo apt-get install -y libnss3-dev
        sudo apt-get install -y xvfb
        sudo apt-get install -y libxss1
        sudo apt-get install -y xdg-utils
        nohup xvfb-run google-chrome-stable http://localhost:3000 &
